#!/usr/bin/env python3
import json, urllib.request, ssl

SUPABASE_URL = "https://cnxeckhygerxdhlahimp.supabase.co"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNueGVja2h5Z2VyeGRobGFoaW1wIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDU5NDUxNiwiZXhwIjoyMDkwMTcwNTE2fQ.zoYYmI4R_2W-aSGNAsMm7J2RpXQqhpGhXOPfJgCqsHk"

articles = [
    {
        "id": "e9eb7407-5a8e-417a-81dc-02c6e9174e6e",
        "content": "OpenAI, uzun süredir beklenen GPT-5.5 modelini resmen tanıttı. Yapay zeka dünyasını kökten değiştirmesi beklenen bu yeni model, çok modlu yetenekleri, dramatik olarak artırılmış bağlam penceresi ve gelişmiş muhakeme kabiliyetleriyle öne çıkıyor.\n\nGPT-5.5, selefi GPT-4o'ya kıyasla birçok kritik alanda ciddi iyileştirmeler sunuyor. Modelin bağlam penceresi 512K token'a çıkarıldı, bu da önceki nesle göre 8 katlık bir artış anlamına geliyor. Bu sayede tam kitapları, uzun yasal belgeleri veya kapsamlı kod tabanlarını tek bir oturumda analiz edebiliyor.\n\nGerçek Zamanlı Ses ve Görüntü İşleme\nModelin en dikkat çekici yeniliklerinden biri gerçek zamanlı ses işleme kapasitesi. Kullanıcılar artık metin yazmak zorunda kalmadan, doğal bir konuşmayla GPT-5.5 ile etkileşime geçebiliyorlar. Ses tonundaki duygusal nüansları bile algılayabilen model, daha insani ve empatik bir deneyim sunuyor.\n\nGörüntü analizi de ciddi şekilde geliştirildi. Tıbbi görüntülerden teknik şemalara, uydu fotoğraflarından mimari planlara kadar geniş bir yelpazede yüksek doğrulukla analiz yapabiliyor. Video işleme konusunda da önemli adımlar atılmış durumda — kısa videoları frame-by-frame analiz edip özetleyebiliyor.\n\nKod Üretimi ve Matematiksel Muhakeme\nGPT-5.5'in kod üretimi kalitesinde muazzam bir sıçrama var. HumanEval benchmark'ında %95'in üzerinde başarı oranına ulaştı ve karmaşık algoritmik problemleri çözme konusunda önceki modelleri geride bıraktı. Matematiksel muhakeme konusunda da MATH benchmark'ında %87'ye ulaşan model, olimpiyat seviyesi problemleri bile çözebiliyor.\n\nGüvenlik ve Erişim\nOpenAI, GPT-5.5'in güvenlik testlerini kapsamlı şekilde tamamladığını belirtiyor. Red team sürecinde 200'den fazla dış araştırmacı modeli saldıya uğrattı. Model halihazırda ChatGPT Plus ve Team kullanıcılarına sunuluyor, API erişimi kademeli olarak açılıyor. Fiyatlandırma konusunda GPT-4o'ya kıyasla token başına maliyetin %40 daha düşük olduğunu vurgulayan OpenAI, geliştiricilerin daha erişilebilir bir şekilde modeli kullanabileceğini ifade ediyor.",
        "category": "Yapay Zeka",
        "image_url": "https://images.unsplash.com/photo-1676299081847-7b1d0c59f7c2?w=800&h=400&fit=crop"
    },
    {
        "id": "63d6c887-c54f-4e3e-b850-beadda5d9bd6",
        "content": "Meta, açık kaynak AI topluluğunu heyecanla beklenilen Llama 4 Scout modelini duyurdu. 17B aktif parametre ve 16 uzmanlı MoE mimarisiyle gelen bu model, performans ve verimlilik arasında benzersiz bir denge kurarak açık kaynak dünyasında yeni bir standart belirledi.\n\nLlama 4 Scout'un en çarpıcı özelliği, 10 milyon token'lık devasa bağlam penceresi. Bu, mevcut tüm açık kaynak modelleri çok geride bırakan bir kapasite ve tam kitapları, büyük kod tabanlarını veya kapsamlı araştırma belgelerini tek bir oturumda işleyebileceğiniz anlamına geliyor.\n\nMixture of Experts (MoE) Mimarisi\nLlama 4 Scout, 16 uzmanlı MoE mimarisiyle her çıkarım sırasında yalnızca 2 uzmanı aktive ediyor. Bu sayede 17B parametreli bir modelin performansını, çok daha küçük bir modele yakın maliyetle sunabiliyor. Çıkarım maliyeti ve hızı, geleneksel yoğun modellere kıyasla ciddi avantajlar sağlıyor.\n\nPerformans ve Benchmark Sonuçları\nMeta'nın açıkladığı benchmark sonuçlarına göre Llama 4 Scout, Gemini 3.1 Flash ve GPT-4o modelleriyle rekabetçi sonuçlar veriyor. MMLU'da %82.3, HumanEval'de %88.7 başarı oranına ulaştı. Özellikle çok dilli görevlerde ve long-context senaryolarında açık ara öne çıkıyor.\n\nAçık Kaynak Taahhüdü\nMeta, Llama 4 Scout'u tamamen açık kaynak olarak yayınladı. Model ağırlıkları, eğitim metodolojisi ve değerlendirme sonuçları herkese açık. Akademik araştırmacılar, bağımsız geliştiriciler ve startup'lar modeli serbestçe kullanabilir ve modify edebilir.\n\nLlama 4 Scout'un daha büyük kardeşi Llama 4 Maverick de yakında duyurulacak. 400B parametreli bu model, GPT-5.5 ve Claude Opus 4.7 ile doğrudan rekabet etmeyi hedefliyor.",
        "category": "Yapay Zeka",
        "image_url": "https://images.unsplash.com/photo-1677442136019-21?w=800&h=400&fit=crop"
    },
    {
        "id": "9397daff-2d1c-4d04-b76f-d7ee12ebcd07",
        "content": "Yapay zeka destekli kod editörleri pazarında amansız bir rekabet yaşanıyor. Cursor ve Windsurf, geliştiricilerin kod yazma deneyimini kökten değiştirmeyi hedefleyen iki güçlü rakip, AI destekli özellikleriyle dikkat çekiyor.\n\nCursor: Deneyimli Geliştiricinin Tercihi\n2023 yılında piyasaya sürülen Cursor, kısa sürede AI editör pazarının lideri konumuna yükseldi. VS Code fork üzerine kurulan editör, mevcut VS Code uzantılarıyla tam uyumlu çalışıyor. En güçlü yanı, tüm kod tabanını analiz edip bağlam-aware öneriler sunabilmesi. Cursor'ın Agent Mode özelliği, birden fazla dosyada eşzamanlı düzenleme yapabiliyor ve terminal komutlarını doğrudan çalıştırabiliyor.\n\nClaude 3.5 Sonnet ve GPT-4o gibi güçlü modellerle entegre çalışan Cursor, özellikle büyük projelerde fark yaratıyor. Cursor Tab özelliği ile satır satır otomatik tamamlama sunarken, Cmd+K kısayoluyla doğal dilde kod yazdırabiliyor. Fiyatlandırma modeli ise aylık 20 USD'den başlıyor.\n\nWindsurf: Yeni Gelenin Güçlü Hamlesi\nCodeium tarafından geliştirilen Windsurf, pazarın en yeni oyuncusu olmasına rağmen hızla dikkat çekmeyi başardı. Flow State konseptiyle geliştiricinin kod yazma akışını bölmeyen bir deneyim sunmayı hedefliyor. Cascade adlı AI asistanını doğrudan editör içine gömüyor, bu sayede bağlam değiştirmeden AI ile etkileşime geçmek mümkün oluyor.\n\nWindsurf'un en büyük avantajı, kişisel kullanım için tamamen ücretsiz olması. Pro planı ise 15 USD/ay seviyesinde.\n\nHangisini Seçmelisiniz?\nEğer büyük bir kod tabanınız varsa ve gelişmiş agent özelliklerine ihtiyaç duyuyorsanız Cursor önde. Ancak bütçe dostu bir alternatif arıyorsanız Windsurf güçlü bir başlangıç noktası sunuyor. Her iki editör de hızla gelişmeye devam ediyor ve bu rekabet geliştiricilerin lehine sonuçlar doğuruyor.",
        "category": "Teknoloji",
        "image_url": "https://images.unsplash.com/photo-1461749280684-dcbe5f5f8f0b?w=800&h=400&fit=crop"
    },
    {
        "id": "c47582e4-225b-46c9-b7af-6b535cb59d35",
        "content": "Anthropic, AI güvenliği ve güvenilirliği konusunda yeni bir çağ açan Claude Opus 4.7 modelini resmen duyurdu. Şirketin amiral gemisi haline gelen bu model, özellikle karmaşık muhakeme, uzun bağlam işleme ve güvenlik alanlarında çığır açıyor.\n\nClaude Opus 4.7'nin en dikkat çekici özelliği, 1 milyon token'lık bağlam penceresi. Bu kapasite ile tam kitapları, yoğun yasal sözleşmeleri ve devasa kod tabanlarını tek bir oturumda analiz edebiliyor. Bağlam penceresinin bu kadar geniş olması, modelin tutarlılığını ve hatırlama kabiliyetini dramatik şekilde artırıyor.\n\nGelişmiş Muhakeme ve Analiz\nOpus 4.7, matematiksel muhakeme ve mantıksal çıkarım alanlarında önceki tüm modelleri geride bırakıyor. ARC-AGI benchmark'ında %72'ye ulaşan model, zincirleme düşünce görevlerinde üstün performans sergiliyor. Bilimsel araştırma yazılarını analiz etme, hukuki belgeleri karşılaştırma ve teknik raporlar hazırlama konularında fark yaratıyor.\n\nModel, aynı zamanda constitutional AI yaklaşımının en gelişmiş versiyonunu kullanıyor. Zararlı içerik üretme, önyargı ve manipülatif yanıt verme eğilimleri ciddi şekilde azaltılmış durumda. Anthropic, modeli 100'den fazla güvenlik testinden geçirdiğini ve elde edilen bulguları kamuoyuyla paylaştığını belirtiyor.\n\nAPI ve Erişim\nClaude Opus 4.7, Anthropic API üzerinden erişime açık. Fiyatlandırma: girdi için 15 USD/million token, çıktı için 75 USD/million token. Ücretsiz katman da mevcut ve geliştiriciler sınırlı kotalarla modeli deneyebiliyor. Ayrıca Opus 4.7 ile birlikte yeni Extended Thinking modu duyuruldu — modelin karmaşık problemleri çözerken düşünme sürecini görünür kılıyor.",
        "category": "Yapay Zeka",
        "image_url": "https://images.unsplash.com/photo-1620712943543-bccbcf5f5f0a?w=800&h=400&fit=crop"
    },
    {
        "id": "d0a2243c-a194-4f75-8b73-d2158a613003",
        "content": "Google, Gemini serisinin en güçlü modeli olan 3.1 Pro'yu duyurdu ve tüm kullanıcılara ücretsiz olarak sunmaya başladı. Bu karar, yapay zeka pazarında erişilebilirliği ve rekabetçiliği yeniden tanımlıyor.\n\nGemini 3.1 Pro, selefine kıyasla pek çok alanda ciddi iyileştirmeler sunuyor. Modelin bağlam penceresi 2 milyon token'a çıkarıldı ve çok modlu işleme kapasitesi dramatik şekilde geliştirildi. Metin, görüntü, ses ve video girdilerini eşzamanlı işleyebilen model, gerçek zamanlı analiz ve üretim konusunda sınıfının en iyisi olduğunu kanıtlıyor.\n\nNeden Ücretsiz?\nGoogle'ın bu hamlesi birkaç stratejik nedene dayanıyor. Birincisi, AI model pazarında OpenAI ve Anthropic karşısında pazar payını korumak ve genişletmek. İkincisi, geniş kullanıcı tabanından elde edilen kullanım verileriyle modeli sürekli iyileştirmek. Üçüncüsü ise Google Cloud altyapısına daha fazla geliştirici çekerek ekosistemi büyütmek.\n\nTeknik Performans\nMMLU benchmark'ında %89.7 başarı oranına ulaşan Gemini 3.1 Pro, GPT-4o ile başa baş gidiyor. Özellikle çok dilli görevlerde, görsel muhakemede ve uzun bağlam işlemede öne çıkıyor. MATH benchmark'ında %85.2'ye ulaşan model, matematiksel problemlerde güçlü sonuçlar veriyor.\n\nGoogle aynı zamanda Gemini 3.1 Flash adlı daha hafif ve hızlı bir modeli de duyurdu. Ücretsiz erişim Gemini API ve Google AI Studio üzerinden sağlanıyor. Geliştiriciler günlük 1.500 ücretsiz istek kullanabiliyor.",
        "category": "Yapay Zeka",
        "image_url": "https://images.unsplash.com/photo-1555949963-aa79dcee801c?w=800&h=400&fit=crop"
    },
    {
        "id": "5ac04e28-b76f-4904-a502-bd24c2aece01",
        "content": "Avrupa Birliği'nin uzun süredir beklenen kapsamlı yapay zeka düzenlemesi AI Act, nihayet yürürlüğe girdi. Dünyanın ilk kapsamlı AI regülasyonu olarak tarihe geçen bu yasal çerçeve, küresel teknoloji endüstrisini derinden etkilemeye aday.\n\nAI Act, yapay zeka sistemlerini risk seviyelerine göre dört kategoriye ayırıyor: kabul edilemez risk, yüksek risk, sınırlı risk ve minimal risk. Her kategori için farklı düzeyde yükümlülükler ve uyum gereksinimleri tanımlanmış durumda.\n\nYüksek Riskli Sistemler\nBiyometrik kimlik doğrulama, kritik altyapı yönetimi, eğitime erişim, istihdam, kamu hizmetleri ve kolluk kuvvetleri gibi alanlarda kullanılan AI sistemleri yüksek riskli olarak sınıflandırılıyor. Bu sistemler şeffaflık, insan gözetimi, veri kalitesi ve belgelendirme gibi sıkı gereksinimlere tabi olacak.\n\nKabul Edilemez Risk\nSosyal puanlama sistemleri, bilinçaltı manipülasyon teknikleri ve gerçek zamanlı biyometrik kitle gözetimi gibi uygulamalar kesinlikle yasaklanıyor. Bu yasaklar, AB'nin temel insan hakları ve demokratik değerleri koruma taahhüdünü yansıtıyor.\n\nŞeffaflık ve Etiketleme\nAI ile üretilmiş içeriklerin etiketlenmesi zorunlu hale geliyor. Deepfake videoları, AI tarafından yazılmış makaleler ve yapay zeka tarafından üretilen görseller açıkça işaretlenecek. Chatbot'lar ve sanal asistanlar, kullanıcıya AI olduklarını belirtmek zorunda.\n\nKüresel Etkiler\nAI Act'in küresel etkileri yadsınamaz. AB pazarına erişmek isteyen tüm uluslararası şirketler bu düzenlemelere uymak zorunda kalacak — tıpkı GDPR'ın gizlilik alanında yarattığı Brussels Effect gibi. Türkiye'de durum henüz net değil ancak AB uyum sürecinde ülkemizin AI Act'e uyum sağlaması bekleniyor.",
        "category": "Genel",
        "image_url": "https://images.unsplash.com/photo-1529107386315-e1c9e8280fc3?w=800&h=400&fit=crop"
    },
    {
        "id": "eb90cc62-8cab-4ee3-adf2-bb6d31b6c59e",
        "content": "Elon Musk'ın yapay zeka şirketi xAI, Grok 4 modelini resmen tanıttı. X platformuyla derinlemesine entegre olan bu model, gerçek zamanlı bilgiye erişim ve sınırsız doğrudan akıl yürütme yetenekleriyle dikkat çekiyor.\n\nGrok 4, önceki Grok modellerinden radikal bir sıçrama sunuyor. Modelin en belirgin özelliği, X platformundaki milyarlarca gönderiye gerçek zamanlı erişimi. Bu sayede en güncel olayları, trendleri ve kampanya bilgiyi anında analiz edip yanıtlayabiliyor. Diğer modellerin aylar süren eğitim verilerinin aksine, Grok 4 şu anı anlıyor.\n\nGerçek Zamanlı Veri Avantajı\nGrok 4'ün X entegrasyonu, modelin güçlü ve zayıf yönlerini aynı anda oluşturuyor. Bir yandan, hiçbir rakibinin erişemediği güncel bilgi akışına sahip. Diğer yandan, sosyal medya verilerinin güvenilirliği sorgulanabilir. xAI, bu sorunu hafifletmek için çoklu kaynak doğrulama mekanizmaları geliştirdiğini belirtiyor.\n\nTeknik Özellikler ve Performans\nGrok 4, 256K token bağlam penceresiyle geliyor. MMLU'da %86.4, HumanEval'de %92.1 başarı oranına ulaşan model, kod üretimi ve mantıksal muhakeme konularında güçlü sonuçlar veriyor. Modelin muhakeme modu karmaşık problemleri çözerken düşünme sürecini adım adım gösteriyor.\n\nErişim ve Fiyatlandırma\nGrok 4, X Premium+ abonelerine ayda 16 USD'den sunuluyor. API erişimi geliştiriciler için mevcut ve girdi başına 5 USD/million token, çıktı için 15 USD/million token fiyatıyla öne çıkıyor. Ücretsiz deneme kotası günlük 100 istekle sınırlı.\n\nxAI'ın stratejisi açık: X'in veri zenginliğini AI yetenekleriyle birleştirip, farklılaşmış bir ürün sunmak. Grok 4'ün gerçek zamanlı bilgi erişimi benzersiz bir avantaj oluğurken, modelin genel muhakeme kalitesinin GPT-5.5 ve Claude Opus 4.7 seviyelerine yaklaştığı görülüyor.",
        "category": "Yapay Zeka",
        "image_url": "https://images.unsplash.com/photo-1617791160536-59ac8f6b9e47?w=800&h=400&fit=crop"
    },
    {
        "id": "f7468243-c95f-4b26-9e32-c43ccd6e1345",
        "content": "Çin yapay zeka şirketi DeepSeek, açık kaynak dünyasında devrim yaratan V4 modelini duyurdu. Model, performansın maliyetsiz olabileceğini kanıtlıyor ve küresel AI endüstrisinin dengesini değiştiriyor.\n\nDeepSeek V4, 671B toplam parametreyle geliştirilmiş olup, MoE mimarisi sayesinde her çıkarım sırasında yalnızca 37B aktif parametre kullanıyor. Bu dramatik verimlilik artışı, modelin performansını kaybetmeden çok düşük maliyetle çalıştırılabilmesini sağlıyor.\n\nAçık Kaynağın Zaferi\nDeepSeek V4'ün en çarpıcı yanı, model ağırlıklarının tamamen açık kaynak olarak yayınlanmış olması. MIT lisansı altında yayınlanan model, ticari kullanım dahil her türlü amaçla serbestçe kullanılabiliyor. Fine-tuning, distillation ve deployment tamamen özgür.\n\nBu kararın küresel etkisi büyük. OpenAI'ın kapalı kaynak stratejisine karşı, açık kaynak topluluğu güçlü bir alternatif elde ediyor. Bağımsız değerlendirmeler, DeepSeek V4'ün GPT-4o ve Claude 3.5 Sonnet modelleriyle rekabetçi, hatta bazı görevlerde onları geçen performans sergilediğini gösteriyor.\n\nEğitim ve Maliyet İnovasyonu\nDeepSeek, modelin eğitiminin yalnızca 5.5 milyon USD'ya mal olduğunu açıkladı — bu, benzer performans seviyesindeki kapalı kaynak modellerin eğitim maliyetinin çok küçük bir kısmı. Şirket, verimli eğitim teknikleri, optimize edilmiş MoE mimarisi ve akıllı veri seçimi stratejileri sayesinde bu maliyet düşüşünü sağladığını belirtiyor.\n\nTürkiye'den Erişim ve Kullanım\nDeepSeek V4, Hugging Face üzerinden indirilebilir ve yerel olarak çalıştırılabilir. 671B parametreli tam model için 8xH100 GPU gerekse de, quantize edilmiş versiyonlar daha mütevazı donanımlarda bile çalıştırılabiliyor. GGUF formatındaki 4-bit quantize versiyon, tek bir A100 veya eşdeğer GPU'da çalışabiliyor.\n\nDeepSeek V4'ün başarısı, açık kaynak AI hareketinin gücünü bir kez daha kanıtlıyor. Kapalı kaynak modellerin hakimiyetine karşı, erişilebilir ve şeffaf alternatiflerin yükselişi devam ediyor.",
        "category": "Yapay Zeka",
        "image_url": "https://images.unsplash.com/photo-1555255707-c0796a81f8c4?w=800&h=400&fit=crop"
    }
]

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

for article in articles:
    aid = article.pop("id")
    data = json.dumps(article, ensure_ascii=False).encode("utf-8")
    url = f"{SUPABASE_URL}/rest/v1/articles?id=eq.{aid}"
    req = urllib.request.Request(url, data=data, method="PATCH")
    req.add_header("apikey", API_KEY)
    req.add_header("Authorization", f"Bearer {API_KEY}")
    req.add_header("Content-Type", "application/json")
    req.add_header("Prefer", "return=minimal")
    try:
        resp = urllib.request.urlopen(req, context=ctx)
        print(f"✓ {aid[:8]}... -> {resp.status}")
    except Exception as e:
        print(f"✗ {aid[:8]}... -> {e}")

print("\nAll articles updated!")